# PlayerUtilities Configuration

# Settings for messages
messages:
  prefix: "&8[&bPlayerUtilities&8] &f"

# Default options for new players
defaults:
  fly-enabled: false
  god-mode: false
  fly-speed: 0.1

# Player data (will be populated automatically)
# Format: UUID: {fly: true/false, godmode: true/false, flyspeed: 0.1-1.0}
players:
# Example:
# 00000000-0000-0000-0000-000000000000:
#   fly: true
#   godmode: false
#   flyspeed: 0.5