name: PlayerUtilities
version: '1.0'
main: com.lozaine.playerutilities.PlayerUtilities
api-version: '1.21'
description: Utilities for player management including fly, godmode, teleport
commands:
  flyspeed:
    description: Adjust your fly speed
    usage: /<command> <speed>
    permission: playerutilities.flyspeed
    aliases: [fs]
  worldtp:
    description: Open a GUI to teleport between worlds
    usage: /<command>
    permission: playerutilities.worldtp
    aliases: [wtp]
  god:
    description: Toggle god mode
    usage: /<command> [player]
    permission: playerutilities.god
  fly:
    description: Toggle fly mode
    usage: /<command> [player]
    permission: playerutilities.fly
permissions:
  playerutilities.flyspeed:
    description: Allows players to change their fly speed
    default: op
  playerutilities.worldtp:
    description: Allows players to teleport between worlds
    default: true
  playerutilities.god:
    description: Allows players to toggle god mode
    default: op
  playerutilities.fly:
    description: Allows players to toggle fly mode
    default: op
  playerutilities.admin:
    description: Gives all permissions
    default: op
    children:
      playerutilities.flyspeed: true
      playerutilities.worldtp: true
      playerutilities.god: true
      playerutilities.fly: true